notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
before_install:
  - sudo apt-get install numpy
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse/
deploy:
  provider: pypi
  skip_cleanup: true
  user: "dwaithe"
  password:
    secure: "ExDjb6d0R/G3M9nJSyEMi/AxPiY2ivz4pAad/R5eic1S7gbRxMtScfuXQ+HjuZxuKTmVcuCmZItOKC2RuqjAmT2sMphizPK1E1DaKISibXsMTP9044n7L5mK4L95RJZnkRlVbhqCaAFDyKAdHBG8xS1G+Ag7kJboscye22uajQHkdnf0aHMnewQ0gVqs0d9bpezZDIuWUr3V2rQZzNGayavFgGH+4f4R2fCzKwflKhE1r8a929V6RV7qPnianYWuKPq3EP4Ufm5aKqiEeGM867JCZysgDxQhyiGwW3wMz5SXbwUGu64zEoTBMxJHIgEnuwATEmO8HW+umw4quzDPdxk9nXHTb3Ak12kA2VdTcXs7s4CemWZ32YiXGves6Bl9NM3uCMgEud9QZpAsZJDKe/zGurqsoUvln4k4+J/tw5fT8stPQaL13NABW8jc/9TpDGuyx2vOH+dG5QJdu+fzTDSYGVDiu4NI5rPbOH9MK74KnwfLCotEfwNW3GVnOD1DvCt+PPoQRcKRvocWiSb5lTLcEgvKW/PxYWrS3Lj61iUqFIMfx6l622Ay619pfiPY1dRcZwZpimx7UiRQQjA+MxNFMlQcbHBx/GFWodOPJyiBiOE8pvULTV8PauuO1HMnAliLzQB+DsMs4OtgsbNXS+2ySDMceW9ZcG5M0Tn4ISs="

